# =========================
# Cấu hình Server / Streamlit
# =========================
server:
  host: "127.0.0.1"       # Host server API
  port: 8000              # Cổng server API

streamlit:
  port: 8501              # Cổng Streamlit app

# =========================
# Model & Embedding
# =========================
model:
  llm_model: "gemma2b-13b"   # Tên LLM dùng cho chat / RAG
  embedding_model: "intfloat/multilingual-e5-small"  # Model embedding
  tokenizer: null             # Nếu cần tokenizer riêng (có thể null)
  RERANK_MODEL :  "cross-encoder/ms-marco-MiniLM-L-6-v2"  # Model rerank
  summary_model: "VietAI/vit5-base" # Model summary
  keywords_model: "intfloat/multilingual-e5-small"  # Model Keywords

# =========================
# Vector DB / FAISS
# =========================
vector_db:
  index_path: "./faiss.index"   # File FAISS local
  metadata_path: "./docs.json"  # Metadata / JSON lưu raw text
  top_k: 3  # Lấy top k result khi retrieve

